FROM resin/rpi-raspbian

RUN apt-get update && apt-get upgrade

# Merged three different installs. In case of errors split up. Removed mariadb-server (separate container)
RUN apt-get install -y apache2 libapache2-mod-php5 php5-gd php5-json php5-mysql php5-curl php5-intl php5-mcrypt php5-imagick

RUN apt-get install -y curl bzip2 ssl-cert

# Download and extract owncloud to /var/www/owncloud
ARG OCVERSION=9.1.2
RUN curl https://download.owncloud.org/community/owncloud-$OCVERSION.tar.bz2 | tar --extract --bzip2 --directory=/var/www

ADD ./owncloud.conf /etc/apache2/sites-available/
RUN ln -s /etc/apache2/sites-available/owncloud.conf /etc/apache2/sites-enabled/owncloud.conf

# Enable apache2 modules
RUN a2enmod rewrite
RUN a2enmod headers
RUN a2enmod env
RUN a2enmod dir
RUN a2enmod mime
RUN service apache2 restart

# Create selfsigned certificate. Need to replace this with Let's Encrypt
RUN make-ssl-cert generate-default-snakeoil
RUN a2enmod ssl
RUN a2ensite default-ssl
RUN service apache2 reload

EXPOSE 80
EXPOSE 443

