FROM resin/rpi-raspbian

# Merged three different installs. In case of errors split up. Removed mariadb-server (separate container)
RUN apt-get update && apt-get install -y apache2 libapache2-mod-php5 php5-gd php5-json php5-mysql php5-curl php5-intl php5-mcrypt php5-imagick curl bzip2 ssl-cert

# Download and extract owncloud to /var/www/owncloud
ARG OCVERSION=9.1.2
RUN curl https://download.owncloud.org/community/owncloud-$OCVERSION.tar.bz2 | tar --extract --bzip2 --directory=/var/www

COPY ./owncloud.conf /etc/apache2/sites-available/
RUN rm --force /etc/apache2/sites-enabled/*
RUN ln --symbolic /etc/apache2/sites-available/owncloud.conf /etc/apache2/sites-enabled/owncloud.conf

# Enable apache2 modules
RUN a2enmod rewrite && a2enmod headers && a2enmod env && a2enmod dir && a2enmod mime

# Create selfsigned certificate. Need to replace this with Let's Encrypt
RUN make-ssl-cert generate-default-snakeoil
RUN a2enmod ssl && a2ensite default-ssl

COPY ./start-server.sh /usr/local/bin/

# Move data directory outside of the www directory for security reasons
RUN mkdir --parents /var/data/owncloud && chown www-data:www-data /var/data/owncloud && chmod 751 /var/data/owncloud

ARG MYSQL_ROOT_PASSWORD
ARG ADMIN_USER
ARG ADMIN_PASSWORD
RUN cd /var/www/owncloud && sudo -u www-data php occ  maintenance:install --database "mysql" --database-name "owncloud"  --database-user "root" --database-host "mysql" --database-pass $MYSQL_ROOT_PASSWORD --admin-user $ADMIN_USER --admin-pass $ADMIN_PASSWORD --data-dir "/var/data/owncloud"

EXPOSE 80 443
VOLUME /var/data/owncloud /var/www/owncloud/apps /var/www/owncloud/config

CMD /usr/local/bin/start-server.sh

