FROM resin/rpi-raspbian

# Merged three different installs. In case of errors split up. Removed mariadb-server (separate container)
RUN apt-get update && apt-get install -y apache2 libapache2-mod-php5 php5-gd php5-json php5-mysql php5-curl php5-intl php5-mcrypt php5-imagick curl bzip2 ssl-cert

# Download and extract owncloud to /var/www/owncloud
ARG OCVERSION=9.1.2
RUN curl https://download.owncloud.org/community/owncloud-$OCVERSION.tar.bz2 | tar --extract --bzip2 --directory=/var/www

COPY ./owncloud.conf /etc/apache2/sites-available/
RUN ln -s /etc/apache2/sites-available/owncloud.conf /etc/apache2/sites-enabled/owncloud.conf

# Enable apache2 modules
RUN a2enmod rewrite && a2enmod headers && a2enmod env && a2enmod dir && a2enmod mime && service apache2 restart

# Create selfsigned certificate. Need to replace this with Let's Encrypt
RUN make-ssl-cert generate-default-snakeoil
RUN a2enmod ssl && a2ensite default-ssl && service apache2 restart

# Run a script to set some environment variables required for apache to start
RUN /etc/apache2/envvars

EXPOSE 80
EXPOSE 443

VOLUME /var/www/owncloud/data
VOLUME /var/www/owncloud/apps

CMD ["/usr/sbin/apache2", "-DFOREGROUND"]

