---

# Install docker
# See also https://docs.docker.com/install/linux/docker-ce/debian

- name: Install docker
  hosts: all
  become: yes
  become_user: root

  tasks:
  - name: Install prerequisite packages
    apt:
      package: "{{ item }}"
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - python-pip

  - name: Add docker signing key
    apt_key:
      url: https://download.docker.com/linux/raspbian/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

  - name: Add docker repository
    apt_repository:
      filename: docker
      repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
      # Need to convert to lowercase, otherwise updating the package index fails with a 404 error
      # Apparently repository entries are case-sensitive...

  - name: Make sure no legacy versions are installed
    apt:
      package: "{{ item }}"
      state: absent
    with_items:
      - docker-engine
      - docker

  - name: Install docker
    apt: 
      package: docker-ce
      update_cache: yes
      state: present

  # Install docker python library (formerly docker-py). This is required for a lot of ansible docker modules to work.
  - name: Install docker python library
    pip:
      name: docker
      state: present

  - name: Create intercontainer network
    docker_network:
      name: intercontainer
      state: present