#!/bin/bash
#
# Wrapper script to allow invocation of all util commands using chrissrv <COMMANDNAME> <ARGUMENTS...>

function check_command() {
	# If parameter is a directory, no command was given at all
	if [ -d "$1" ]
	then
		echo "No command specified"
		exit 1
	fi
	if [ ! -e "$1" ]
	then
		echo "Unknown command: $(basename $1)"
		exit 1
	fi
}

# Get canonical path of command script
# Use realpath to resolve symbolic links first
CMD="$(dirname $(realpath $0))/$1"
check_command "$CMD"

shift # Remove <COMMANDNAME> from arguments
exec "$CMD" "$@"