#!/bin/bash
#
# Helper script to execute a command (param 2 and following) after a delay (param 1) in a new process
# Useful for delaying udev scripts

DELAY=$1
shift # Shift delay out of arguments

(sleep $DELAY && "$@") & disown